#!/usr/bin/env bash
set -euo pipefail

# Portable setup script for windy-skill
# Generated by digest-system init

echo "Setting up windy-skill..."

# Detect Node.js
NODE=$(command -v node || echo "")
if [ -z "$NODE" ]; then
  # Common non-standard locations (Synology NAS, etc.)
  for p in /volume1/@appstore/Node.js_v20/usr/local/bin/node \
           /usr/local/bin/node /opt/node/bin/node; do
    [ -x "$p" ] && NODE="$p" && break
  done
fi

if [ -z "$NODE" ]; then
  echo "ERROR: Node.js not found. Install Node.js >= 16."
  exit 1
fi

echo "Using Node.js: $NODE ($($NODE --version))"

# Install dependencies
npm install --production 2>/dev/null || $NODE $(command -v npm) install --production

# Link CLI globally
npm link 2>/dev/null || echo "Link failed — run with sudo or use: $NODE $(pwd)/bin/windy-skill.js"

echo "Done! Test with: windy auth"
